config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :categories, only: [:index, :show]
  resources :discussions, only: [:new, :show, :create]
  resources :posts, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]

  get '*path', to: 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :discussions

  def total_threads
    self.discussions.count
  end

  def total_posts
    total_posts = []
    self.discussions.each do |disc|
      total_posts << disc.posts.length
    end
    total_posts.inject(:+)
  end

  # def last_post
  #   self.discussions.last
  # end

end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :category
  has_many :posts
  has_many :users, through: :posts
  acts_as_punchable

  # last post
  def last_post
    if self.posts.length > 0
      self.posts.last.updated_at.localtime.strftime('%H:%M:%S - %m/%d/%Y')
    else
      "Thread is empty!"
    end
  end

  # count total number of posts in discussion/thread
  def total_posts
    self.posts.count
  end

  # count all unique users who have posted in thread (although this is already unique?)
  def total_users
    self.users.uniq.count
  end

  # display page views of certain discussion/thread (using gem punching_bag)
  def page_views
    self.hits
  end

  # average time between posts...measures user engagement
  def avg_tm_btwn_posts
    if self.posts.length == 0
      "No posts!"
    elsif self.posts.length == 1
      "Only one post!"
    else
      updated_at_times = self.posts.each_with_object([]) do |post, arr|
        arr << post.updated_at
      end

      differences = [] # can do this using each_with_object.with_index
      updated_at_times.each_with_index do |time, i|
        if i < updated_at_times.length - 1
          differences << updated_at_times[i + 1] - time
        end
      end

      avg_time = differences.inject(:+) / differences.length
      avg_time.to_i
    end
  end

  # average post length
  def avg_post_length
    if self.posts.length > 0
      post_lengths = self.posts.each_with_object([]) do |post, arr|
        arr << post.content.length
      end

      avg_length = post_lengths.inject(:+) / post_lengths.length
      avg_length.to_i.to_s + ' characters'
    else
      'No posts!'
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :discussion


  def read_time
    self.content.reading_time
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :discussions, through: :posts
  validates :username, uniqueness: true
  validates :username, presence: true
  validates :password, length: { minimum: 8 }, allow_nil: false
  has_secure_password

  def recent_five_posts
    self.posts.last(5).reverse
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :get_current_user

  def get_current_user
    if @current_user
      @current_user
    else
      @current_user = User.find_by(id: cookies[:user_id])
      # if @current_user
      #   @current_user = @current_user.username
      # end
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    if Category.where(id: params[:id]).exists?
      @category = Category.find(params[:id])
    else
      redirect_to categories_path
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

  def new
    @discussion = Discussion.new
  end

  def show
    if Discussion.where(id: params[:id]).exists?
      @discussion = Discussion.find(params[:id])
      @discussion.punch(request)
    else
      redirect_to categories_path
    end
  end

  def create
    @discussion = Discussion.create(discussion_params)
    redirect_to category_path(@discussion.category)
  end

  private

  def discussion_params
    params.require(:discussion).permit(:title, :category_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    redirect_to discussion_path(@post.discussion)
  end

  def destroy
    @post = Post.find(params[:id]).destroy
    redirect_to discussion_path(@post.discussion)
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :discussion_id, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      cookies[:user_id] = @user.id
      redirect_to categories_path
    else
      flash.notice = 'No user found with that name/password combination'
      redirect_to login_path
    end
  end

  def destroy
    cookies.clear
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      cookies[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @recents = @user.recent_five_posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :profile_image_url, :bio, :birthdate, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<div class='ui container'>
  <div class='ui segment'>
  <h1>All Discussion Topics</h1>
  </div>
  <div class='ui segment'>
  <div class="ui relaxed divided list">
    <% @categories.each do |cat| %>
      <div class="item">
        <div class="content">
          <a><%= link_to cat.title, category_path(cat), class: 'header' %></a>
          <div class="description">
            <b>Threads:</b> <%= cat.total_threads %> | <b>Posts:</b> <%= cat.total_posts %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/categories/show.html.erb
<div class='ui container'>
  <div class='ui segment'>
    <h1><%= link_to 'All', categories_path %> > <%= @category.title %></h1>
  </div>
  <div class='ui segment'>
  <div class="ui relaxed divided list">
    <% @category.discussions.each do |dis| %>
      <div class="item">
        <div class="content">
          <a><%= link_to dis.title, discussion_path(dis), class: 'header' %></a>
          <div class="description">
            <b>Posts:</b> <%= dis.total_posts %> | <b>Users in this thread:</b> <%= dis.total_users %> | <b>Last Post:</b> <%= dis.last_post %>
          </div>
        </div>
      </div>
    <% end %>
  </div>


<% if cookies[:user_id] %>
  <%= render partial: "layouts/new_discussion", locals: { discussion: Discussion.new, cat_id: @category.id } %>
<% end %>

</div>
</div>

app/views/discussions/new.html.erb
<h1>Create New Discussion</h1>
<%= form_for @discussion do |f| %>
  <%= f.collection_select :category_id, Category.all, :id, :title %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/discussions/show.html.erb
<div class='main ui container'>
  <div class="ui raised segment">
    <div class="ui right rail">
      <div class='ui segments' id='thread-right-rail'>
        <div class="ui segment">
          Posts: <%= @discussion.posts.count %>
        </div>
        <div class="ui segment">
          Users in this thread: <%= @discussion.users.uniq.count %>
        </div>
        <div class="ui segment">
          Average seconds between posts: <%= @discussion.avg_tm_btwn_posts %>
        </div>
        <div class="ui segment">
          Average length of posts: <%= @discussion.avg_post_length %>
        </div>
        <div class='ui segment'>
          Page views: <%= @discussion.hits %>
        </div>
      </div>
    </div>
    <h1><%= link_to 'All', categories_path %> > <%= link_to @discussion.category.title, category_path(@discussion.category) %> > <%= @discussion.title %></h1>
  </div>

  <% post_count = 0 %>
  <% @discussion.posts.each do |pst| %>
    <% post_count += 1 %>
    <div class='ui raised segments'>
      <div class='ui segment'>
        <%= '# ' + post_count.to_s %><br>
        <%= pst.content.reading_time :format => :long %>
      </div>
      <div class='ui segment'>
        <p><%= pst.content %></p>
      </div>
      <div class='ui secondary segment'>
        <div class='post_author'>By: <img class="ui avatar image" src=<%= pst.user.profile_image_url %>> <%= link_to pst.user.username, user_path(pst.user) %>
          <% if cookies[:user_id].to_i == pst.user_id %>
            <%= link_to "(delete post)", pst, method: :delete %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>


<% if cookies[:user_id] %>
  <%= render partial: "layouts/new_post", locals: { post: Post.new, disc_id: @discussion.id, user_id: cookies[:user_id] } %>
<% end %>

</div>

app/views/layouts/_errors.html.erb
<% if new_object.errors %>
  <% new_object.errors.full_messages.each do |error| %>
    <div class="ui error form segment">
      <div class="ui error message">
        <div class="header">Error Message(s)</div>
        <p><%= error %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_new_discussion.html.erb
<div class='ui form'>
  <%= form_for discussion, :html => {class: 'ui input focus'} do |f| %>
    <%= f.hidden_field :category_id, value: cat_id %>
    <%= f.text_field :title, placeholder: 'Thread Title' %>
    <%= f.submit 'Create Thread' %>
  <% end %>
</div>

app/views/layouts/_new_edit_user.html.erb
<%= render partial: 'layouts/errors', locals: { new_object: @user } %>

<div class='ui form segment'>
  <%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :username %>
    <%= f.text_field :username %><br>
    <%= f.label :profile_image_url %>
    <%= f.text_field :profile_image_url %>
    <%= f.label :birthdate %>
    <%= f.text_field :birthdate %><br>
    <%= f.label :bio %>
    <%= f.text_area :bio %><br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit class: 'ui button' %>
  <% end %>
</div>

app/views/layouts/_new_post.html.erb
<div class='ui form segment' id='new-post-entry'>
    <%= form_for post, :html => {class: 'ui input focus'} do |f| %>
      <%= f.hidden_field :user_id, value: user_id %>
      <%= f.hidden_field :discussion_id, value: disc_id %>
      <%= f.text_area :content %>
      <%= f.submit %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarForum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <div class="ui borderless main menu">
      <a><%= link_to 'Autalk', categories_path, class: 'item' %></a>
      <div class="item right">
        <% if cookies[:user_id] %>
          <div id='logged-in-text'>You are logged in as <%= link_to User.find(cookies[:user_id]).username, user_path(cookies[:user_id]) %> <img class="ui avatar image" src=<%= User.find(cookies[:user_id]).profile_image_url %>></div>
          <div><%= link_to 'Logout', logout_path, class: 'ui button', method: 'delete' %></div>
        <% else %>
          <div><%= link_to 'Login', login_path, class: 'ui button' %></div>
        <% end %>
      </div>
    </div>
  </head>

  <body id='body-image'>
    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Create New Post</h1>
    <%= form_for @post do |f| %>
      <%= f.collection_select :user_id, User.all, :id, :username %>
      <%= f.collection_select :discussion_id, Discussion.all, :id, :title %>
      <%= f.label :content %>
      <%= f.text_area :content %>
      <%= f.submit %>
    <% end %>
  </body>
</html>

app/views/users/edit.html.erb
<div class='ui container'>
  <div class='ui segment'>
    <h1>Edit User</h1>
  </div>
  <%= render 'layouts/new_edit_user' %>
</div>

app/views/users/new.html.erb
<div class='ui container'>
  <div class='ui segment'>
    <h1>Create New User</h1>
  </div>
  <%= render 'layouts/new_edit_user' %>
</div>

app/views/users/show.html.erb
<div class='ui container'>
  <div class='ui segment'>
    <h1><%= @user.username %></h1>
  </div>
  <div class='ui segment'>
    <div class='ui ribbon label'>Details</div>
    <% if cookies[:user_id].to_i == @user.id %>
      <%= link_to "Edit User", edit_user_path(@user) %> <br>
    <% end %>

    <img class="ui small circular image pad-down" src="<% if @user.profile_image_url %>
      <%= @user.profile_image_url %>
    <% end %>">

    <% if @user.name %>
      <h4 class='pad-down'>Real Name:</h4> <%= @user.name %>
    <% end %>

    <% if @user.birthdate %>
      <h4>Birth Day:</h4> <%= @user.birthdate %>
    <% end %>

    <% if @user.bio %>
      <h4>Bio:</h4>
      <p><%= @user.bio %></p>
    <% end %>
  </div>

  <div class='ui segment'>
    <h3>Total posts: <%= @user.posts.length %></h3>

    <h3>Recent Posts</h3>
    <ul>
      <% @recents.each do |pst| %>
        <li>
          <%= link_to pst.discussion.category.title, category_path(pst.discussion.category) %> > <%= link_to pst.discussion.title, discussion_path(pst.discussion) %><br>
          <%= pst.updated_at.strftime('%m/%d/%Y at %I:%M') %> - <%= pst.content[0..50] + '...' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>